name: CICD for Nodejs 


on:
  push:
    branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use node js
        uses: actions/setup-node@v1
        with:
         node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm install
          npm run build

        env: 
          CI: true   


  depoly:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
     - name: executing remote ssh commands using password
       uses: appleboy/ssh-action@v0.1.8
       with:
          host: ec2-100-26-223-242.compute-1.amazonaws.com
          username:  ubuntu
          key:  -----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
QyNTUxOQAAACAa911D9hjav4rwYEahToE9gYBMU7OYOUMUJ6QXj2E+PwAAAKAQ6oE3EOqB
NwAAAAtzc2gtZWQyNTUxOQAAACAa911D9hjav4rwYEahToE9gYBMU7OYOUMUJ6QXj2E+Pw
AAAECxJ9rzNt1XrzvaSL0E5l5EHFw2M2y17WiOgOqHvSMdthr3XUP2GNq/ivBgRqFOgT2B
gExTs5g5QxQnpBePYT4/AAAAHG11aGFtbWVkcmFtZWV6MjAwMEBnbWFpbC5jb20B
-----END OPENSSH PRIVATE KEY-----
          port: 22
          script: |
              curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
              . ~/.nvm/nvm.sh

               nvm instal 14
               npm install -g pm2
               cd ~/CICD
               git pull origin main
               npm install
               npm run build
               pm2 restart api
            



